apiVersion: v1
kind: Secret
metadata:
  name: vpn-secrets
  namespace: nexoryx-vpn
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: CHANGE_ME
  WIREGUARD_PUBLIC_KEY: CHANGE_ME
  OPENVPN_USERNAME: admin
  OPENVPN_PASSWORD: CHANGE_ME
  GRAFANA_ADMIN_PASSWORD: CHANGE_ME
